---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rono-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rono-validator
  template:
    metadata:
      labels:
        app: rono-validator
    spec:
      containers:
        - name: validator
          image: majedur708/hlf-api:500.8
          env:
            - name: API_BASE
              value: http://api.default.svc.cluster.local:4000
            - name: ROA_FILE
              value: /data/roas.json       # Changed to /data
          volumeMounts:
            - name: data
              mountPath: /data             # Changed from /app to /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gortr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gortr
  template:
    metadata:
      labels:
        app: gortr
    spec:
      containers:
        - name: gortr
          image: cloudflare/gortr:latest
          args:
            - -bind
            - :8282
            - -cache
            - /data/roas.json        # Changed to /data
            - -checktime=false
            - -sloppy
            - -verify=false
            - -verify.key=""              # disables signature verification if needed
      # For TLS:
           # - -tls.bind=:443
     # - -tls.cert=/path/to/cert.pem
      # - -tls.key=/path/to/key.pem  
          volumeMounts:
            - name: data
              mountPath: /data         # Changed from /app to /data
          readinessProbe:
            tcpSocket:
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc

---
apiVersion: v1
kind: Service
metadata:
  name: gortr
spec:
  selector:
    app: gortr
  ports:
    - name: rtr
      port: 8282
      targetPort: 8282
