---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rono-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rono-validator
  template:
    metadata:
      labels:
        app: rono-validator
    spec:
      containers:
        - name: validator
          image: majedur708/hlf-api:500.8
          env:
            - name: API_BASE
              value: http://api.default.svc.cluster.local:4000
            - name: ROA_FILE
              value: /data/roas.json
          volumeMounts:
            - name: data
              mountPath: /data
            - name: keys
              mountPath: /app/keys     # where cert.pem and private.pem live
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
        - name: keys
          persistentVolumeClaim:
            claimName: keys-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gortr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gortr
  template:
    metadata:
      labels:
        app: gortr
    spec:
      containers:
        - name: gortr
          image: cloudflare/gortr:latest
          args:
            - -bind
            - :8282
            - -cache
            - /data/roas.json
            - -checktime=false
            - -verify=true
            - -verify.key
            - /keys/cert.pem
          volumeMounts:
            - name: data
              mountPath: /data
            - name: keys
              mountPath: /keys         # required for cert.pem access
          readinessProbe:
            tcpSocket:
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
        - name: keys
          persistentVolumeClaim:
            claimName: keys-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gortr
spec:
  selector:
    app: gortr
  ports:
    - name: rtr
      port: 8282
      targetPort: 8282
