apiVersion: apps/v1
kind: Deployment
metadata:
  name: stayrtr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stayrtr
  template:
    metadata:
      labels:
        app: stayrtr
    spec:
      containers:
        - name: stayrtr
          image: rpki/stayrtr:latest
          args:
            - -cache
            - /app/data/rpki.json
            - -bind
            - :8282
            - -checktime=false
          volumeMounts:
            - name: data
              mountPath: /app/data
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc


---
apiVersion: v1
kind: Service
metadata:
  name: stayrtr
spec:
  selector:
    app: stayrtr
  ports:
    - name: rtr
      port: 8282
      targetPort: 8282

