
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gobgp-config
data:
  gobgp.conf: |
    [global.config]
      as = 65001
      router-id = "192.0.2.1"
      listen-port = -1  # Disable binding to port 179 to avoid permission issues

    [[neighbors]]
      [neighbors.config]
        neighbor-address = "192.0.2.2"
        peer-as = 65002

---
apiVersion: v1
kind: Pod
metadata:
  name: gobgp
  labels:
    app: gobgp
spec:
  restartPolicy: Always
  containers:
    - name: gobgp
      image: jauderho/gobgp:latest
      command: ["gobgpd", "-f", "/gobgp/gobgp.conf"]
      ports:
        - containerPort: 179
        - containerPort: 50051
      securityContext:
        runAsUser: 0
        capabilities:
          add: ["NET_BIND_SERVICE"]
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "200m"
      volumeMounts:
        - name: gobgp-conf
          mountPath: /gobgp/gobgp.conf
          subPath: gobgp.conf
  volumes:
    - name: gobgp-conf
      configMap:
        name: gobgp-config

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp
spec:
  selector:
    app: gobgp
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp-api
  template:
    metadata:
      labels:
        app: gobgp-api
    spec:
      containers:
        - name: gobgp-api
          image: majedur708/hlf-api:50.6  # Replace with your actual image
          ports:
            - containerPort: 2000
          env:
            - name: GOBGPD_ADDR
              value: "gobgp:50051"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp-api
spec:
  selector:
    app: gobgp-api
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP
  type: ClusterIP





# # =========================
# # RONO CONFIGURATION
# # =========================
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: gobgp-config-rono
# data:
#   gobgp.conf: |
#     [global.config]
#       as = 64000
#       router-id = "192.0.1.1"

#     [[neighbors]]
#       [neighbors.config]
#         neighbor-address = "192.0.2.2"
#         peer-as = 64501

#     [[neighbors]]
#       [neighbors.config]
#         neighbor-address = "192.0.4.2"
#         peer-as = 64502

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gobgp-rono
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gobgp-rono
#   template:
#     metadata:
#       labels:
#         app: gobgp-rono
#     spec:
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
#       containers:
#         - name: gobgp
#           image: jauderho/gobgp:latest
#           command: ["gobgpd", "-f", "/gobgp/gobgp.conf"]
#           ports:
#             - containerPort: 179
#             - containerPort: 50051
#           securityContext:
#             runAsUser: 0
#             capabilities:
#               add: ["NET_BIND_SERVICE"]
#           volumeMounts:
#             - name: gobgp-config
#               mountPath: /gobgp/
#               readOnly: true
#           resources:
#             requests:
#               memory: "100Mi"
#               cpu: "100m"
#             limits:
#               memory: "200Mi"
#               cpu: "200m"
#       volumes:
#         - name: gobgp-config
#           configMap:
#             name: gobgp-config-rono
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gobgp-rono
# spec:
#   selector:
#     app: gobgp-rono
#   ports:
#     - name: bgp
#       port: 179
#       targetPort: 179
#     - name: grpc
#       port: 50051
#       targetPort: 50051
#   clusterIP: None

# # =========================
# # AFRINIC CONFIGURATION
# # =========================
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: gobgp-config-afrinic
# data:
#   gobgp.conf: |
#     [global.config]
#       as = 64501
#       router-id = "192.0.2.2"

#     [[neighbors]]
#       [neighbors.config]
#         neighbor-address = "192.0.1.1"
#         peer-as = 64000

#     [[neighbors]]
#       [neighbors.config]
#         neighbor-address = "192.0.3.1"
#         peer-as = 65010

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gobgp-afrinic
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gobgp-afrinic
#   template:
#     metadata:
#       labels:
#         app: gobgp-afrinic
#     spec:
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
#       containers:
#         - name: gobgp
#           image: jauderho/gobgp:latest
#           command: ["gobgpd", "-f", "/gobgp/gobgp.conf"]
#           ports:
#             - containerPort: 179
#             - containerPort: 50051
#           securityContext:
#             runAsUser: 0
#             capabilities:
#               add: ["NET_BIND_SERVICE"]
#           volumeMounts:
#             - name: gobgp-config
#               mountPath: /gobgp/
#               readOnly: true
#           resources:
#             requests:
#               memory: "100Mi"
#               cpu: "100m"
#             limits:
#               memory: "200Mi"
#               cpu: "200m"
#       volumes:
#         - name: gobgp-config
#           configMap:
#             name: gobgp-config-afrinic
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gobgp-afrinic
# spec:
#   selector:
#     app: gobgp-afrinic
#   ports:
#     - name: bgp
#       port: 179
#       targetPort: 179
#     - name: grpc
#       port: 50051
#       targetPort: 50051
#   clusterIP: None

# # =========================
# # BRAC CONFIGURATION
# # =========================
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: gobgp-config-brac
# data:
#   gobgp.conf: |
#     [global.config]
#       as = 65010
#       router-id = "192.0.3.1"

#     [[neighbors]]
#       [neighbors.config]
#         neighbor-address = "192.0.2.2"
#         peer-as = 64501

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gobgp-brac
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gobgp-brac
#   template:
#     metadata:
#       labels:
#         app: gobgp-brac
#     spec:
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
#       containers:
#         - name: gobgp
#           image: jauderho/gobgp:latest
#           command: ["gobgpd", "-f", "/gobgp/gobgp.conf"]
#           ports:
#             - containerPort: 179
#             - containerPort: 50051
#           securityContext:
#             runAsUser: 0
#             capabilities:
#               add: ["NET_BIND_SERVICE"]
#           volumeMounts:
#             - name: gobgp-config
#               mountPath: /gobgp/
#               readOnly: true
#           resources:
#             requests:
#               memory: "100Mi"
#               cpu: "100m"
#             limits:
#               memory: "200Mi"
#               cpu: "200m"
#       volumes:
#         - name: gobgp-config
#           configMap:
#             name: gobgp-config-brac
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gobgp-brac
# spec:
#   selector:
#     app: gobgp-brac
#   ports:
#     - name: bgp
#       port: 179
#       targetPort: 179
#     - name: grpc
#       port: 50051
#       targetPort: 50051
#   clusterIP: None

# # =========================
# # GoBGP API SERVER
# # =========================
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gobgp-api
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gobgp-api
#   template:
#     metadata:
#       labels:
#         app: gobgp-api
#     spec:
#       containers:
#         - name: gobgp-api
#           image: majedur708/hlf-api:50.3  # Replace with your actual image
#           ports:
#             - containerPort: 2000
#           env:
#             - name: GOBGP_INSTANCES
#               value: "rono=gobgp-rono:50051,afrinic=gobgp-afrinic:50051,brac=gobgp-brac:50051"
#             - name: GOBGPD_DEFAULT
#               value: "rono"
#           resources:
#             requests:
#               memory: "250Mi"
#               cpu: "200m"
#             limits:
#               memory: "350Mi"
#               cpu: "300m"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gobgp-api
# spec:
#   selector:
#     app: gobgp-api
#   ports:
#     - port: 2000
#       targetPort: 2000
#       protocol: TCP
#   type: ClusterIP
 