apiVersion: v1
kind: ConfigMap
metadata:
  name: gobgp-config
data:
  router1.conf: |
    [global.config]
      as = 65001
      router-id = "192.0.2.1"

    [[neighbors]]
      [neighbors.config]
        neighbor-address = "192.0.2.2"
        peer-as = 65002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp
  template:
    metadata:
      labels:
        app: gobgp
    spec:
      containers:
      - name: gobgp
        image: jauderho/gobgp:latest
        command: ["/bin/sh", "-c"]
        args:
          - gobgpd -f /gobgp/router1.conf --api-hosts 0.0.0.0:50051 --log-level debug
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: config-volume
          mountPath: /gobgp/router1.conf
          subPath: router1.conf
      volumes:
      - name: config-volume
        configMap:
          name: gobgp-config

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp-service
spec:
  selector:
    app: gobgp
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gobgp-router
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gobgp-router
#   template:
#     metadata:
#       labels:
#         app: gobgp-router
#     spec:
#       containers:
#         - name: gobgp-router
#           image: majedur708/hlf-api:300.44
#           ports:
#             - containerPort: 50051   
#             - containerPort: 50052   
#             - containerPort: 50053   
#             - containerPort: 50054   
#             - containerPort: 50055  
#             - containerPort: 50056   
#             - containerPort: 50057
#             - containerPort: 50058
#             - containerPort: 50059
#             - containerPort: 50060
#             - containerPort: 50061
#             - containerPort: 50062
#             - containerPort: 50063
#             - containerPort: 50064
#             - containerPort: 50065
#             - containerPort: 50066
#             - containerPort: 50067
            
#           resources:
#             requests:
#               memory: "250Mi"
#               cpu: "200m"
#             limits:
#               memory: "350Mi"
#               cpu: "300m"          
#           securityContext:
#             runAsUser: 0
#             capabilities:
#               add: ["NET_BIND_SERVICE"]

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gobgp-service
# spec:
#   selector:
#     app: gobgp-router
#   ports:
#     - name: grpc
#       port: 50051
#       targetPort: 50051
#       protocol: TCP
#   type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp-api
  template:
    metadata:
      labels:
        app: gobgp-api
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: gobgp-api
          image: majedur708/hlf-api:50.28
          ports:
            - containerPort: 2000
          env:
            - name: GOBGPD_ADDR
              value: "gobgp-service:50051"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "300m"
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/connection-profile
              subPath: connection-profile
            - name: data
              mountPath: /organizations
              subPath: organizations

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp-api
spec:
  selector:
    app: gobgp-api
  ports:
    - name: http
      port: 2000
      targetPort: 2000
      protocol: TCP
  type: ClusterIP

