apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp-router
  template:
    metadata:
      labels:
        app: gobgp-router
    spec:
      containers:
        - name: gobgp-router
          image: majedur708/hlf-api:300.44
          ports:
            - containerPort: 50051   
            - containerPort: 50052   
            - containerPort: 50053   
            - containerPort: 50054   
            - containerPort: 50055  
            - containerPort: 50056   
            - containerPort: 50057
            - containerPort: 50058
            - containerPort: 50059
            - containerPort: 50060
            - containerPort: 50061
            - containerPort: 50062
            - containerPort: 50063
            - containerPort: 50064
            - containerPort: 50065
            - containerPort: 50066
            - containerPort: 50067
            
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "300m"          
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["NET_BIND_SERVICE"]

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp-service
spec:
  selector:
    app: gobgp-router
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp-api
  template:
    metadata:
      labels:
        app: gobgp-api
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: gobgp-api
          image: majedur708/hlf-api:50.28
          ports:
            - containerPort: 2000
          env:
            - name: GOBGPD_ADDR
              value: "gobgp-service:50051"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "300m"
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/connection-profile
              subPath: connection-profile
            - name: data
              mountPath: /organizations
              subPath: organizations

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp-api
spec:
  selector:
    app: gobgp-api
  ports:
    - name: http
      port: 2000
      targetPort: 2000
      protocol: TCP
  type: ClusterIP



# important note:
# curl -X POST http://localhost:2000/announce   -H "Content-Type: application/json"   -d '{"prefix": "192.168.100.0", "prefixLen": 24, "nextHop": "127.0.0.11", "asPath": [100, 200, 300]}'
# {"details":"rpc error: code = Unimplemented desc = unknown service apipb.GobgpApi","error":"failed to add path"}% 



# majedurrahman@Majedurs-Mac-mini gobgp-router % kubectl port-forward services/gobgp-service 50051:50051
# Forwarding from 127.0.0.1:50051 -> 50051
# Forwarding from [::1]:50051 -> 50051
# Handling connection for 50051


# majedurrahman@Majedurs-Mac-mini gobgp-api % gobgp neighbor  -p 50051
# Peer        AS  Up/Down State       |#Received  Accepted
# 127.0.0.12 200 00:15:08 Establ      |        0         0
# 127.0.0.14 400 00:15:08 Establ      |        0         0
# majedurrahman@Majedurs-Mac-mini gobgp-api % 

# inside gobgp-router container:
# gobgp-router-546fdbb6bc-7hwnc:/gobgp# gobgp neighbor -p 50051
# Peer        AS  Up/Down State       |#Received  Accepted
# 127.0.0.12 200 00:00:55 Establ      |        0         0
# 127.0.0.14 400 00:00:55 Establ      |        0         0
# gobgp-router-546fdbb6bc-7hwnc:/gobgp# gobgp neighbor -p 50052
# Peer        AS  Up/Down State       |#Received  Accepted
# 127.0.0.11 100 00:00:59 Establ      |        0         0
# 127.0.0.13 300 00:00:59 Establ      |        0         0
# 127.0.0.15 500 00:00:59 Establ      |        0         0
# gobgp-router-546fdbb6bc-7hwnc:/gobgp# gobgp neighbor -p 50053
# Peer        AS  Up/Down State       |#Received  Accepted
# 127.0.0.12 200 00:01:01 Establ      |        0         0
# 127.0.0.16 600 00:01:01 Establ      |        0         0
# gobgp-router-546fdbb6bc-7hwnc:/gobgp# gobgp neighbor -p 50054
# Peer        AS  Up/Down State       |#Received  Accepted
# 127.0.0.11 100 00:01:04 Establ      |        0         0
# 127.0.0.15 500 00:01:04 Establ      |        0         0
# gobgp-router-546fdbb6bc-7hwnc:/gobgp# gobgp neighbor -p 50055
# Peer        AS  Up/Down State       |#Received  Accepted
# 127.0.0.12 200 00:01:06 Establ      |        0         0
# 127.0.0.14 400 00:01:06 Establ      |        0         0
# 127.0.0.16 600 00:01:06 Establ      |        0         0
# gobgp-router-546fdbb6bc-7hwnc:/gobgp# 

# used version
# github.com/osrg/gobgp/v3 v3.37.0