apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp-router
  template:
    metadata:
      labels:
        app: gobgp-router
    spec:
      containers:
        - name: gobgp-router
          image: majedur708/hlf-api:300.40  
          ports:
            - containerPort: 50051   
            - containerPort: 50052   
            - containerPort: 50053   
            - containerPort: 50054   
            - containerPort: 50055  
            - containerPort: 50056   
            - containerPort: 50057
            - containerPort: 50058
            - containerPort: 50059
            - containerPort: 50060
            - containerPort: 50061
            - containerPort: 50062
            - containerPort: 50063
            - containerPort: 50064
            - containerPort: 50065
            - containerPort: 50066
            - containerPort: 50067
            
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "300m"          
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["NET_BIND_SERVICE"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobgp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp-api
  template:
    metadata:
      labels:
        app: gobgp-api
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: gobgp-api
          image: majedur708/hlf-api:50.20
          ports:
            - containerPort: 2000
          env:
            - name: GOBGPD_ADDR
              value: "gobgp-service:50051"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "300m"
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/connection-profile
              subPath: connection-profile
            - name: data
              mountPath: /organizations
              subPath: organizations

---
apiVersion: v1
kind: Service
metadata:
  name: gobgp-api
spec:
  selector:
    app: gobgp-api
  ports:
    - name: http
      port: 2000
      targetPort: 2000
      protocol: TCP
  type: ClusterIP

