---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-afrinic
  labels:
    app: chaincode-basic-afrinic
spec:
  selector:
    matchLabels:
      app: chaincode-basic-afrinic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-afrinic
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.49
          imagePullPolicy: Always
          name: chaincode-basic-afrinic
          env:
            - name: CHAINCODE_ID
              value: "basic:9e3e0aeefd8a6991b499b590aa94d107051c81742c53ccf488c9a971ecc627f7"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
