---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-afrinic
  labels:
    app: chaincode-basic-afrinic
spec:
  selector:
    matchLabels:
      app: chaincode-basic-afrinic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-afrinic
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.55
          imagePullPolicy: Always
          name: chaincode-basic-afrinic
          env:
            - name: CHAINCODE_ID
              value: "basic:c9a8d10f0f4d956aca655b238e67a5029ea05836755d67518f01ace6a7cc164d"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
