---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-apnic
  labels:
    app: chaincode-basic-apnic
spec:
  selector:
    matchLabels:
      app: chaincode-basic-apnic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-apnic
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.49
          name: chaincode-basic-apnic
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:93b5880e982cd81fa4bad4fa680308cfb5b81e3965cadd379abf4c8b1c6812cd"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
