---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org2
  labels:
    app: chaincode-basic-org2
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org2
    spec:
      containers:
        - image: majedur708/hlf-api:18.0.32
          name: chaincode-basic-org2
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:cc896c5c897c964b0121052ef27ce32f71235b420fff1cfd3966d8e3089c1d91"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
