---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-apnic
  labels:
    app: chaincode-basic-apnic
spec:
  selector:
    matchLabels:
      app: chaincode-basic-apnic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-apnic
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.55
          name: chaincode-basic-apnic
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:9cdc47d49891551ec34982238996d1380d578e64f9a1c76ff9319946150ee72d"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
