---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-arin
  labels:
    app: chaincode-basic-arin
spec:
  selector:
    matchLabels:
      app: chaincode-basic-arin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-arin
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.55
          name: chaincode-basic-arin
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:c19a69b1b13f655eb3c8dadfb7f29ecc10f9a8eddb3731f82da8877a55288fd0"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
