---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org3
  labels:
    app: chaincode-basic-org3
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org3
    spec:
      containers:
        - image: majedur708/hlf-api:18.0.37
          name: chaincode-basic-org3
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:3fe7c2c80d2a6483a4277aa6700dc5e273b233b2bd6d8d6bea405e6657cfc5bd"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
