---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-ripencc
  labels:
    app: chaincode-basic-ripencc
spec:
  selector:
    matchLabels:
      app: chaincode-basic-ripencc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-ripencc
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.55
          name: chaincode-basic-ripencc
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:13d6a9462c5ff8c28f30a2661afe1dac71b150ccab5314be6085c8243bf53c81"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
