---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org4
  labels:
    app: chaincode-basic-org4
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org4
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.46
          name: chaincode-basic-org4
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:eb96bf4b687e1203d5268e0bdedeadd13d4fcebaf6e4727f62f694bbe620a1fe"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
