---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org4
  labels:
    app: chaincode-basic-org4
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org4
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.42
          name: chaincode-basic-org4
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:288dc200939566187264a87901b6d9f1ac09404ddf4ab30c1de85463f096edcb"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
