---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-lacnic
  labels:
    app: chaincode-basic-lacnic
spec:
  selector:
    matchLabels:
      app: chaincode-basic-lacnic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-lacnic
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.56
          name: chaincode-basic-lacnic
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:7f10fc787d4bf1363b87079bc8b6acd5a7128ba84cc9726fe339cbbd5fc1a9b0"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
