---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org5
  labels:
    app: chaincode-basic-org5
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org5
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.47
          name: chaincode-basic-org5
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:b27867509f932c48c4732c122796b8a0a94154241ac2f7e1b99fd4abe17039be"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
