---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-lacnic
  labels:
    app: chaincode-basic-lacnic
spec:
  selector:
    matchLabels:
      app: chaincode-basic-lacnic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-lacnic
    spec:
      containers:
        - image: majedur708/hlf-api:18.100.48
          name: chaincode-basic-lacnic
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:9dce5af2102e60255ab8b5366927369a81b4a64e44cb88612a4d3f40fab99563"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
