---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org6
  labels:
    app: chaincode-basic-org6
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org6
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org6
    spec:
      containers:
        - image: majedur708/hlf-api:18.0.3
          name: chaincode-basic-org6
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:b1c70f91ca616c20bde2528f2a6075c234da48cb1c5b2e052edb6f9e6bd62021"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
