--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: basic-rono
  labels:
    app: basic-rono
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-basic-rono
