apiVersion: apps/v1
kind: Deployment
metadata:
    name: orderer5
spec:
    selector:
        matchLabels:
            name: orderer5
    replicas: 1
    template:
        metadata:
            labels:
                name: orderer5
        spec:
           volumes:
             - name: fabricfiles
               persistentVolumeClaim:
                  claimName: mypvc
           containers:
             - image: hyperledger/fabric-orderer:2.4.9
               name: orderer5
               imagePullPolicy: IfNotPresent
               env:
                - name: CONFIGTX_ORDERER_ADDRESSES
                  value: "orderer5:7050"
                - name: ORDERER_GENERAL_LISTENADDRESS
                  value: "0.0.0.0"
                - name: ORDERER_GENERAL_LISTENPORT
                  value: "7050"
                - name: ORDERER_GENERAL_LOGLEVEL
                  value: debug
                - name: ORDERER_GENERAL_LOCALMSPDIR
                  value: /organizations/ordererOrganizations/rono.com/orderers/orderer5.rono.com/msp
                - name: ORDERER_GENERAL_LOCALMSPID
                  value: OrdererMSP
                - name: ORDERER_GENERAL_GENESISMETHOD
                  value: file
                - name: ORDERER_GENERAL_GENESISFILE
                  value: /system-genesis-block/genesis.block
                - name: ORDERER_GENERAL_TLS_ENABLED
                  value: "true"
                - name: ORDERER_GENERAL_TLS_PRIVATEKEY
                  value: /organizations/ordererOrganizations/rono.com/orderers/orderer5.rono.com/tls/server.key
                - name: ORDERER_GENERAL_TLS_CERTIFICATE
                  value: /organizations/ordererOrganizations/rono.com/orderers/orderer5.rono.com/tls/server.crt
                - name: ORDERER_GENERAL_TLS_ROOTCAS
                  value: /organizations/ordererOrganizations/rono.com/orderers/orderer5.rono.com/tls/ca.crt
                - name:  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
                  value: /organizations/ordererOrganizations/rono.com/orderers/orderer5.rono.com/tls/server.key
                - name:  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
                  value: /organizations/ordererOrganizations/rono.com/orderers/orderer5.rono.com/tls/server.crt
               
               resources:
                 limits:
                    memory: "400Mi"
                    cpu: "400m"
                 requests:
                    memory: "350Mi"
                    cpu: "300m"              
               
               volumeMounts:
                - name:  fabricfiles
                  mountPath:  /organizations
                  subPath: organizations
          
                - name: fabricfiles
                  mountPath: /system-genesis-block
                  subPath: system-genesis-block
