apiVersion: v1
kind: Service
metadata:
  name: ca-org5
  
  labels:
    app: ca-org5
spec:
  type: ClusterIP
  selector:
    app: ca-org5
  ports:
    - protocol: TCP
      targetPort: 12054
      port: 12054