apiVersion: v1
kind: Service
metadata:
  name: ca-apnic
  labels:
    app: ca-apnic
spec:
  type: ClusterIP
  selector:
    app: ca-apnic
  ports:
    - protocol: TCP
      targetPort: 8054
      port: 8054