apiVersion: v1
kind: Service
metadata:
  name: ca-org4
  
  labels:
    app: ca-org4
spec:
  type: ClusterIP
  selector:
    app: ca-org4
  ports:
    - protocol: TCP
      targetPort: 11054
      port: 11054