apiVersion: v1
kind: Service
metadata:
  name: ca-rono
  
  labels:
    app: ca-rono
spec:
  type: ClusterIP
  selector:
    app: ca-rono
  ports:
    - protocol: TCP
      targetPort: 13054
      port: 13054