apiVersion: v1
kind: Service
metadata:
  name: ca-ripencc
  
  labels:
    app: ca-ripencc
spec:
  type: ClusterIP
  selector:
    app: ca-ripencc
  ports:
    - protocol: TCP
      targetPort: 11054
      port: 11054