apiVersion: v1
kind: Service
metadata:
  name: ca-lacnic
  
  labels:
    app: ca-lacnic
spec:
  type: ClusterIP
  selector:
    app: ca-lacnic
  ports:
    - protocol: TCP
      targetPort: 12054
      port: 12054