apiVersion: v1
kind: Service
metadata:
  name: ca-arin
  
  labels:
    app: ca-arin
spec:
  type: ClusterIP
  selector:
    app: ca-arin
  ports:
    - protocol: TCP
      targetPort: 9054
      port: 9054