apiVersion: v1
kind: Service
metadata:
  name: ca-org6
  
  labels:
    app: ca-org6
spec:
  type: ClusterIP
  selector:
    app: ca-org6
  ports:
    - protocol: TCP
      targetPort: 13054
      port: 13054