apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-org6
spec:
  selector:
    matchLabels:
      app: ca-org6
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-org6
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
      containers:

        - name: ca-org6
          image: hyperledger/fabric-ca:1.5.13
          imagePullPolicy: "Always"
          command:
            [
              "fabric-ca-server" ,
              "start", "-b" ,"admin:adminpw","--port","13054", "-d"
            ]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
           - name: FABRIC_CA_SERVER_CA_NAME
             value: ca-org6
           - name: FABRIC_CA_SERVER_TLS_ENABLED
             value: "true"
           - name: FABRIC_CA_SERVER_CSR_CN
             value: "ca-org6"
           - name: FABRIC_CA_SERVER_CSR_HOSTS
             value: "ca-org6"
          volumeMounts:
            - name: data
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/org6