apiVersion: v1
kind: Service
metadata:
  name: ca-afrinic
  labels:
    app: ca-afrinic
spec:
  type: ClusterIP
  selector:
    app: ca-afrinic
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054