apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/
    server: 159.89.174.36

# local deployment


# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mypv
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 20Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   hostPath: 
#     path: /mnt/data/ 
#     type: DirectoryOrCreate

    
   