kind: Service
apiVersion: v1
metadata:
  name: peer0-rono
  labels:
    app: peer0-rono
spec:
  selector:
    name: peer0-rono
  type: ClusterIP
  ports:
    - name: grpc
      port: 14051
      targetPort: 14051   
      protocol: TCP
    - name: event
      port: 7061         
      targetPort: 7061   
      protocol: TCP
    - name: couchdb
      port: 5984         
      targetPort: 5984  
      protocol: TCP

---
#---------------- Peer0 org5 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-rono
    metrics-service: "true"
  name: peer0-rono-metrics
spec:
  type: ClusterIP
  ports:
  - name: "peer-metrics"
    port: 9443
    targetPort: 9443
  selector:
    name: peer0-rono