kind: Service
apiVersion: v1
metadata:
  name: peer0-org4
  labels:
    app: peer0-org4
spec:
  selector:
    name: peer0-org4
  type: ClusterIP
  ports:
    - name: grpc
      port: 12051
      protocol: TCP
    - name: event
      port: 7061
      protocol: TCP
    - name: couchdb
      port: 5984
      protocol: TCP

---
#---------------- Peer0 org4 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-org4
    metrics-service: "true"
  name: peer0-org4-metrics
spec:
  type: ClusterIP
  ports:
  - name: "peer-metrics"
    port: 9443
    targetPort: 9443
  selector:
    name: peer0-org4