apiVersion: v1
kind: ConfigMap
metadata:
  name: caliper-config
  labels:
    app: caliper
data:
  caliper-network.yaml: |
    name: Caliper Benchmarks
    version: "2.0.0"
    caliper:
      blockchain: fabric

    channels:
      - channelName: mychannel
        contracts:
          - id: basic

    organizations:
      - mspid: Org1MSP
        identities:
          certificates:
            - name: 'Admin'
              clientPrivateKey:
                path: '/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk'
              clientSignedCert:
                path: '/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem'
        connectionProfile:
          path: '/usr/src/app/connection-profile/connection-org1.yaml'
          discover: true

  config.yaml: |
    simpleArgs: &simple-args
      name: "System Manager"
      email: "sysmgr@example.com"
      orgMSP: "Org1MSP"
      role: "rir"
      createdAt: "2025-06-21T10:00:00Z"

    test:
      name: system-manager-benchmark
      description: Performance benchmark for SystemManager chaincode
      workers:
        number: 1
      rounds:
        - label: createSystemManager
          txNumber: 100
          rateControl:
            type: fixed-rate
            opts:
              tps: 10
          workload:
            module: benchmarks/scenario/systemmanager/create.js
            arguments: *simple-args

 