apiVersion: v1
kind: ConfigMap
metadata:
  name: caliper-config
  labels:
    app: caliper
data:
  caliper-network.yaml: |
    name: Caliper Benchmarks
    version: "2.0.0"
    caliper:
      blockchain: fabric

    channels:
      - channelName: mychannel
        contracts:
          - id: basic

    organizations:
      - mspid: Org1MSP
        identities:
          certificates:
            - name: 'User1'
              clientPrivateKey:
                path: '/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
              clientSignedCert:
                path: '/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem'
        connectionProfile:
          path: '/usr/src/app/connection-profile/connection-org1.json'
          discover: false

      - mspid: Org2MSP
        identities:
          certificates:
            - name: 'User1'
              clientPrivateKey:
                path: '/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk'
              clientSignedCert:
                path: '/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/cert.pem'
        connectionProfile:
          path: '/usr/src/app/connection-profile/connection-org2.json'
          discover: false

      - mspid: Org3MSP
        identities:
          certificates:
            - name: 'User1'
              clientPrivateKey:
                path: '/organizations/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/keystore/priv_sk'
              clientSignedCert:
                path: '/organizations/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/signcerts/cert.pem'
        connectionProfile:
          path: '/usr/src/app/connection-profile/connection-org3.json'
          discover: false

      - mspid: Org4MSP
        identities:
          certificates:
            - name: 'User1'
              clientPrivateKey:
                path: '/organizations/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/keystore/priv_sk'
              clientSignedCert:
                path: '/organizations/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/signcerts/cert.pem'
        connectionProfile:
          path: '/usr/src/app/connection-profile/connection-org4.json'
          discover: false

      - mspid: Org5MSP
        identities:
          certificates:
            - name: 'User1'
              clientPrivateKey:
                path: '/organizations/peerOrganizations/org5.example.com/users/User1@org5.example.com/msp/keystore/priv_sk'
              clientSignedCert:
                path: '/organizations/peerOrganizations/org5.example.com/users/User1@org5.example.com/msp/signcerts/cert.pem'
        connectionProfile:
          path: '/usr/src/app/connection-profile/connection-org5.json'
          discover: false

      - mspid: Org6MSP
        identities:
          certificates:
            - name: 'User1'
              clientPrivateKey:
                path: '/organizations/peerOrganizations/org6.example.com/users/User1@org6.example.com/msp/keystore/priv_sk'
              clientSignedCert:
                path: '/organizations/peerOrganizations/org6.example.com/users/User1@org6.example.com/msp/signcerts/cert.pem'
        connectionProfile:
          path: '/usr/src/app/connection-profile/connection-org6.json'
          discover: false

  config.yaml: |
    simpleArgs: &simple-args
      userId: "20000"
      name: "System Manager"
      email: "sysmgr@example.com"
      orgMSP: "Org1MSP"
      role: "rir"
      createdAt: "2025-06-21T10:00:00Z"

    test:
      name: system-manager-benchmark
      description: Performance benchmark for SystemManager chaincode
      workers:
        number: 10
      rounds:
        - label: createSystemManager (fixed-load)
          txDuration: 30
          rateControl:
            type: fixed-load
            opts:
              transactionLoad: 2500
          workload:
            module: benchmarks/scenario/systemmanager/create.js
            arguments: *simple-args
          timeout:
            transaction: 180
            endorsement: 180

        - label: createSystemManager (fixed-rate)
          txDuration: 30
          rateControl:
            type: fixed-rate
            opts:
              tps: 2500
          workload:
            module: benchmarks/scenario/systemmanager/create.js
            arguments: *simple-args
          timeout:
            transaction: 180
            endorsement: 180

        - label: getSystemManager (fixed-load)
          txDuration: 30
          rateControl:
            type: fixed-load
            opts:
              transactionLoad: 2500
          workload:
            module: benchmarks/scenario/systemmanager/query.js
            arguments:
              userId: "100"
          timeout:
            transaction: 180
            endorsement: 180

        - label: getSystemManager (fixed-rate)
          txDuration: 30
          rateControl:
            type: fixed-rate
            opts:
              tps: 2500
          workload:
            module: benchmarks/scenario/systemmanager/query.js
            arguments:
              userId: "100"
          timeout:
            transaction: 180
            endorsement: 180
