kind: Service
apiVersion: v1
metadata:
  name: peer0-lacnic
  labels:
    app: peer0-lacnic
spec:
  selector:
    name: peer0-lacnic
  type: ClusterIP
  ports:
    - name: grpc
      port: 13051
      targetPort: 13051   
      protocol: TCP
    - name: event
      port: 7061         
      targetPort: 7061   
      protocol: TCP
    - name: couchdb
      port: 5984         
      targetPort: 5984  
      protocol: TCP

---
#---------------- Peer0 lacnic Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-lacnic
    metrics-service: "true"
  name: peer0-lacnic-metrics
spec:
  type: ClusterIP
  ports:
  - name: "peer-metrics"
    port: 9443
    targetPort: 9443
  selector:
    name: peer0-lacnic